version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    ignore:
      - dependency-name: php-actions/phpunit
        versions: ["7", "8", "9"]
  - package-ecosystem: composer
    directory: /
    schedule:
      interval: daily
