language: php
php:
- 7.1
- 7.2
- 7.3
- 7.4
before_script:
- composer self-update
- composer install
deploy:
  provider: heroku
  app: letterboxd-ical
  on:
    php: 7.4
  api_key:
    secure: Nr2Q2tvyhs/XNszqOWrWARHnRKNewZPYs5hnkOmv/ZKuk1k6SOG7ki10bhLI4AS2s7+WE3NAhuHIwJZzFRuYojekuJSAQY9WESvc7Q3Oofi59q1AZ+nEkU3Q7CJ87vPizF3LleHiYTweT3n4zdY8Y6sBGJDfvwLmMa/H0nfBMAI=
