title: Chris Buckley
description: letterboxd-ics is a package to render a Letterboxd diary in iCalendar format.

url: https://cmbuckley.co.uk
baseurl: /letterboxd-ics

repository: cmbuckley/letterboxd-ics
remote_theme: "cmbuckley/cmbuckley.github.io"

plugins:
  - jekyll-github-metadata
  - jekyll-remote-theme

markdown: kramdown
highlighter: rouge

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
