name: Build
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    name: Test (PHP ${{ matrix.php-versions }})
    strategy:
      matrix:
        php-versions:
          - 8.0
          - 8.1
    steps:
      - uses: actions/checkout@v3
      - uses: php-actions/composer@v6
        with:
          php_extensions: zip
      - uses: php-actions/phpunit@v6
        with:
          php_version: ${{ matrix.php-versions }}
          php_extensions: zip
  deploy:
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    needs: test
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: flyctl deploy
        run: |
          flyctl secrets set LETTERBOXD_USERNAME=$LETTERBOXD_USERNAME LETTERBOXD_PASSWORD=$LETTERBOXD_PASSWORD
          flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          LETTERBOXD_USERNAME: ${{ secrets.LETTERBOXD_USERNAME }}
          LETTERBOXD_PASSWORD: ${{ secrets.LETTERBOXD_PASSWORD }}
